#!/usr/bin/env python3

import argparse
import hashlib
import json
import os
import re
import subprocess
from subprocess import Popen 
import sys
import traceback
from urllib.error import HTTPError
from urllib.request import Request, urlopen

def llm_completion(prompt, api_config):
    api_key = "none"
    if not api_key:
        raise ValueError("Please set the OPENAI_API_KEY environment variable.")

    headers = {
        "Authorization": f"Bearer {api_config['key']}",
        "Content-Type": "application/json",
    }

    while api_config['url'][-1] == "/":
        api_config['url'] = api_config['url'][:-1]

    url = api_config['url'] + "/v1/responses"
    payload = api_config['payload'].copy()


    payload['input'] = [ { "role": "user", "content": prompt } ]

    data = json.dumps(payload).encode("utf-8")
    req = Request(
            url,
            data=data,
            headers=headers,
            method="POST",
            )
    try:
        with urlopen(req) as response:
            res_body = response.read().decode("utf-8")
            res_json = json.loads(res_body)
            code = res_json["output"][-1]["content"][-1]["text"]

            code = re.findall(r"```python\n[^`]*```", code)[-1]
            code = code[len("```python\n"):-len("```")]
            return code

    except HTTPError as e:
        error_info = e.read().decode("utf-8")
        raise RuntimeError(
            f"API Error (Status {e.code}): {error_info}"
        ) from e


parser = argparse.ArgumentParser("nq",
    description="same as jq, but make queries with natural language"
)
parser.add_argument(
    "-db",
    "--debug",
    action="store_true",
    help="print generated code to stderr (set always_debug to true in ~/.config/nq/config.json to make it default)"
)
parser.add_argument(
    "-nl",
    "--no-log",
    action="store_true",
    help="disable log, even if log_path is not null in ~/.config/nq/config.json"
)
parser.add_argument(
    "prompt",
    type=str,
    nargs='*',
)
args = parser.parse_args()
home = os.path.expanduser("~")

with open(f"{home}/.config/nq/template.md", "r") as f:
    template = f.read()
with open(f"{home}/.config/nq/api.json", "r") as f:
    api_config = json.load(f)

with open(f"{home}/.config/nq/config.json", "r") as f:
    config = json.load(f)

user_prompt = " ".join(args.prompt).strip()
prompt = template.replace("{{prompt}}", user_prompt)

try:
    reply = llm_completion(prompt, api_config)

    if config["sandbox"]:
        cmd = [
                "bwrap",
                "--ro-bind", "/usr", "/usr",
                "--symlink", "usr/lib64", "/lib64",
                "--unshare-all",
                "--new-session",
                "python3", "-c", reply
                ]
    else:
        cmd = ["python3", "-c", reply]

    process = subprocess.Popen(
        cmd,
        stdin=sys.stdin,
        text=True
    )

    process.communicate()

    if config['log_path'] is not None and not args.no_log:
        log_path = os.path.expanduser(config['log_path'])
        with open(log_path, 'a') as f:
            f.write(json.dumps({
                "prompt": user_prompt,
                "template_sha256": hashlib.sha256(template.encode()).hexdigest()[:32],
                "payload": api_config['payload'],
                "output": reply,
                })+"\n")

        
except Exception as e:
    print(f"An error occurred: {e}")
    traceback.print_exc()
finally:
    if (args.debug or config['always_debug']) and 'reply' in globals():
        is_interactive = sys.stderr.isatty()
        if is_interactive:
            print("\033[36m", end='', file=sys.stderr)
        header  = "#!/usr/bin/env python3\n"
        print(header + reply.strip(), file=sys.stderr)
        if is_interactive:
            print("\033[0m", end='', file=sys.stderr)

