#!/usr/bin/env python3

import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
import os
import re
import subprocess
from subprocess import Popen 
import sys
from time import time
import traceback
from urllib.error import HTTPError
from urllib.request import Request, urlopen

def filter_code(code):
    code = re.findall(r"```python\n[^`]*```", code)[-1]
    code = code[len("```python\n"):-len("```")]
    return code

def llm_request(prompt, api_config):
    api_key = "none"
    if not api_key:
        raise ValueError("Please set the OPENAI_API_KEY environment variable.")

    headers = {
        "Authorization": f"Bearer {api_config['key']}",
        "Content-Type": "application/json",
    }
    while api_config['url'][-1] == "/":
        api_config['url'] = api_config['url'][:-1]
    url = api_config['url'] + "/v1/responses"
    payload = api_config['payload'].copy()
    payload['input'] = [ { "role": "user", "content": prompt } ]
    data = json.dumps(payload).encode("utf-8")
    req = Request(
            url,
            data=data,
            headers=headers,
            method="POST",
            )
    try:
        with urlopen(req) as response:
            res_body = response.read().decode("utf-8")
            res_json = json.loads(res_body)
            text = res_json["output"][-1]["content"][-1]["text"]
            return text

    except HTTPError as e:
        error_info = e.read().decode("utf-8")
        raise RuntimeError(
            f"API Error (Status {e.code}): {error_info}"
        ) from e

def batch_llm_request(batch, api_config):
    def _request(prompt):
        return llm_request(prompt, api_config)
    with ThreadPoolExecutor(max_workers=len(batch)) as executor:
        return list(executor.map(_request, batch))

home = os.path.expanduser("~")
with open(f"{home}/.config/nq/api.json", "r") as f:
    api_config = json.load(f)

parser = argparse.ArgumentParser("nq",
    description="make queries with natural language"
)
parser.add_argument(
    "-l",
    "--language",
    action="store_true",
    help="parse the lines using the LLM instead of creating a Python program"
)
parser.add_argument(
    "-0",
    "--null",
    action="store_true",
    help="use NULL as entry splitter instead of newline (language mode only)"
)
parser.add_argument(
    "-bs",
    "--batch_size",
    default=None,
    type=int,
    metavar="NUM",
)
parser.add_argument(
    "-db",
    "--debug",
    action="store_true",
    help="print generated code to stderr (set always_debug to true in ~/.config/nq/config.json to make it default)"
)
parser.add_argument(
    "-t",
    "--template",
    type=str,
    default=None,
    metavar="PATH"
)
parser.add_argument(
    "-nl",
    "--no-log",
    action="store_true",
    help="disable log, even if log_path is not null in ~/.config/nq/config.json"
)
parser.add_argument(
    "-m",
    "--model",
    type=str,
    default=api_config['default'],
    choices=[x for x in api_config if x != 'default']
)
parser.add_argument(
    "prompt",
    type=str,
    nargs='*',
)
args,_ = parser.parse_known_args()

api_config = api_config[args.model]

if args.template is not None:
    with open(args.template, "r") as f:
        template = f.read()
else:
    if args.language:
        with open(f"{home}/.config/nq/language_template.md", "r") as f:
            template = f.read()
    else:
        with open(f"{home}/.config/nq/template.md", "r") as f:
            template = f.read()


with open(f"{home}/.config/nq/config.json", "r") as f:
    config = json.load(f)

if "python_cmd" not in config:
    config["python_cmd"] = "python3"

if args.batch_size is None:
    batch_size = config['batch_size']
else:
    batch_size = args.batch_size

user_prompt = " ".join(args.prompt).strip()


if args.language:
    inputs = []
    prompts = []
    i = 0

    if args.null:
        sep = '\0'
    else:
        sep = '\n'
    v = sys.stdin.read().strip(sep).split(sep)
    start = time()
    for line in v:
        inputs.append(line.strip())
        prompt = template.replace("{{prompt}}", user_prompt)
        prompt = prompt.replace("{{data}}", line.strip())
        prompts.append(prompt)
        if len(prompts) >= batch_size:
            reply = batch_llm_request(prompts, api_config)
            for x in zip(inputs, reply):
                print(json.dumps({"i": i, "in":x[0], "out":x[1].strip()}, ensure_ascii=False))
                i += 1

            dt = int((len(v) - i) * (time()-start)/i)
            sec = dt % 60
            min = (dt // 60) % 60
            h = dt // 3600

            if i < len(v):
                str_dt = ""
                if h > 0:
                    str_dt += f"{h}h "
                if min > 0:
                    str_dt += f"{min}m "
                if sec > 0:
                    str_dt += f"{sec}s "
                print(f'{int(100 * i / len(v)):4d}%, ETA: {str_dt}\r', file=sys.stderr, end='')

            prompts = []
            inputs = []

    if len(inputs) > 0:
        reply = batch_llm_request(prompts, api_config)
        for x in zip(inputs, reply):
            print(json.dumps({"i": i, "in":x[0],"out":x[1].strip()}, ensure_ascii=False))
            i += 1

    print(f'                                          \r', file=sys.stderr, end='')
else:

    # try to match regex
    for regex_pattern in config["regex_routing"]:

        def parse_arg(arg, argv, prompt, word_regex, join_str):
            if "[]" in  arg:
                return [ arg.replace("[]", x) for x in argv ]

            m = re.search("\\[[0-9]+\\]", arg)
            if m is not None:
                i = int(m[0][1:-1])
                return [ re.sub("\\[[0-9]+\\]", argv[i], arg) ]

            m = re.search("\\[[0-9]+:\\]", arg)
            if m is not None:
                i0 = int(m[0][1:-2])
                return [ re.sub("\\[[0-9]+:\\]", x, arg) for x in argv[i0:] ]

            m = re.search("\\[:[0-9]+\\]", arg)
            if m is not None:
                i1 = int(m[0][2:-1])
                return [ re.sub("\\[:[0-9]+\\]", x, arg) for x in argv[:i1] ]

            m = re.search("\\[[0-9]+:[0-9]+\\]", arg)
            if m is not None:
                i0 = int(m[0].split(":")[0][1:])
                i1 = int(m[0].split(":")[1][:-1])
                return [ re.sub("\\[:[0-9]+\\]", x, arg) for x in argv[i0:i1] ]

            if "{}" in  arg:
                arg = arg.replace("{}", user_prompt)

            v = re.findall(word_regex, user_prompt)
            m = re.search("{[0-9]+}", arg)
            while m is not None:
                i = int(m[0][1:-1])
                arg = arg.replace(m[0], v[i])
                m = re.search("{[0-9]+}", arg)

            m = re.search("{[0-9]+:}", arg)
            while m is not None:
                i0 = int(m[0][1:-2])
                arg = arg.replace(m[0], join_str.join(v[i0:]))
                m = re.search("{[0-9]+:}", arg)

            m = re.search("{:[0-9]+}", arg)
            while m is not None:
                i1 = int(m[0][2:-1])
                arg = arg.replace(m[0], join_str.join(v[:i1]))
                m = re.search("{:[0-9]+}", arg)

            m = re.search("{[0-9]+:[0-9]+}", arg)
            while m is not None:
                i0 = int(m[0].split(":")[0][1:])
                i1 = int(m[0].split(":")[1][:-1])
                arg = arg.replace(m[0], join_str.join(v[i0:i1]))
                m = re.search("{[0-9]+:[0-9]+}", arg)

            return [arg]


        if re.search(regex_pattern, user_prompt) is not None:
            cmd = config["regex_routing"][regex_pattern]["cmd"]
            if "word" not in config["regex_routing"][regex_pattern]:
                config["regex_routing"][regex_pattern]["word"] = "[^ ]"
            if "join" not in config["regex_routing"][regex_pattern]:
                config["regex_routing"][regex_pattern]["join"] = " "
            cmd = [
                x for v in [
                    parse_arg(x,
                              [y for y in sys.argv if y != '-db' and y != "--debug"],
                              user_prompt,
                              config["regex_routing"][regex_pattern]["word"],
                              config["regex_routing"][regex_pattern]["join"]) for x in cmd
                ] for x in v
            ]
            process = subprocess.Popen(
                cmd,
                stdin=sys.stdin,
                text=True
            )

            process.communicate()
            sys.stdout.flush()
            sys.stderr.flush()

            if (args.debug or config['always_debug']):
                is_interactive = sys.stderr.isatty()
                if is_interactive:
                    print("\033[36m", end='', file=sys.stderr)
                header  = "#!/usr/bin/env python3\n"
                #print(f"REGEX MATCH ({regex_pattern})\n{json.dumps(config["regex_routing"][regex_pattern], indent=2)}\n{cmd}", file=sys.stderr)
                print(f"REGEX MATCH ({regex_pattern})\ncmd={cmd}\ndescription: {config['regex_routing'][regex_pattern]['description']}", file=sys.stderr)
                if is_interactive:
                    print("\033[0m", end='', file=sys.stderr)

            exit(0)





    prompt = template.replace("{{prompt}}", user_prompt)
    try:
        reply = filter_code(llm_request(prompt, api_config))

        if config["sandbox"]:
            cmd = [
                    "bwrap",
                    "--ro-bind", "/usr", "/usr",
                    "--symlink", "usr/lib64", "/lib64",
                    "--unshare-all",
                    "--new-session",
                    config["python_cmd"], "-c", reply
                    ]
        else:
            cmd = [config["python_cmd"], "-c", reply]

        process = subprocess.Popen(
            cmd,
            stdin=sys.stdin,
            text=True
        )

        process.communicate()

        if config['log_path'] is not None and not args.no_log:
            log_path = os.path.expanduser(config['log_path'])
            with open(log_path, 'a') as f:
                f.write(json.dumps({
                    "prompt": user_prompt,
                    "template_sha256": hashlib.sha256(template.encode()).hexdigest()[:32],
                    "payload": api_config['payload'],
                    "output": reply,
                    })+"\n")

            
    except Exception as e:
        traceback.print_exc()
    finally:
        if (args.debug or config['always_debug']) and 'reply' in globals():
            is_interactive = sys.stderr.isatty()
            if is_interactive:
                print("\033[36m", end='', file=sys.stderr)
            header  = "#!/usr/bin/env python3\n"
            print(header + reply.strip(), file=sys.stderr)
            if is_interactive:
                print("\033[0m", end='', file=sys.stderr)

