#!/usr/bin/env python3

import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
import os
import re
import subprocess
from subprocess import Popen 
import sys
from time import time
import traceback
from urllib.error import HTTPError
from urllib.request import Request, urlopen

def filter_code(code):
    code = re.findall(r"```python\n[^`]*```", code)[-1]
    code = code[len("```python\n"):-len("```")]
    return code

def llm_request(prompt, api_config):
    api_key = "none"
    if not api_key:
        raise ValueError("Please set the OPENAI_API_KEY environment variable.")

    headers = {
        "Authorization": f"Bearer {api_config['key']}",
        "Content-Type": "application/json",
    }
    while api_config['url'][-1] == "/":
        api_config['url'] = api_config['url'][:-1]
    url = api_config['url'] + "/v1/responses"
    payload = api_config['payload'].copy()
    payload['input'] = [ { "role": "user", "content": prompt } ]
    data = json.dumps(payload).encode("utf-8")
    req = Request(
            url,
            data=data,
            headers=headers,
            method="POST",
            )
    try:
        with urlopen(req) as response:
            res_body = response.read().decode("utf-8")
            res_json = json.loads(res_body)
            text = res_json["output"][-1]["content"][-1]["text"]
            return text

    except HTTPError as e:
        error_info = e.read().decode("utf-8")
        raise RuntimeError(
            f"API Error (Status {e.code}): {error_info}"
        ) from e

def batch_llm_request(batch, api_config):
    def _request(prompt):
        return llm_request(prompt, api_config)
    with ThreadPoolExecutor(max_workers=len(batch)) as executor:
        return list(executor.map(_request, batch))

parser = argparse.ArgumentParser("nq",
    description="make queries with natural language"
)
parser.add_argument(
    "-l",
    "--language",
    action="store_true",
    help="parse the lines using the LLM instead of creating a Python program"
)
parser.add_argument(
    "-0",
    "--null",
    action="store_true",
    help="use NULL as entry splitter instead of newline (language mode only)"
)
parser.add_argument(
    "-bs",
    "--batch_size",
    default=32,
    type=int,
    help="batch size for language mode"
)
parser.add_argument(
    "-db",
    "--debug",
    action="store_true",
    help="print generated code to stderr (set always_debug to true in ~/.config/nq/config.json to make it default)"
)
parser.add_argument(
    "-nl",
    "--no-log",
    action="store_true",
    help="disable log, even if log_path is not null in ~/.config/nq/config.json"
)
parser.add_argument(
    "prompt",
    type=str,
    nargs='*',
)
args = parser.parse_args()
home = os.path.expanduser("~")

if args.language:
    with open(f"{home}/.config/nq/language_template.md", "r") as f:
        template = f.read()
else:
    with open(f"{home}/.config/nq/template.md", "r") as f:
        template = f.read()

with open(f"{home}/.config/nq/api.json", "r") as f:
    api_config = json.load(f)

with open(f"{home}/.config/nq/config.json", "r") as f:
    config = json.load(f)

user_prompt = " ".join(args.prompt).strip()


if args.language:
    inputs = []
    prompts = []
    i = 0

    if args.null:
        sep = '\0'
    else:
        sep = '\n'
    v = sys.stdin.read().strip(sep).split(sep)
    start = time()
    for line in v:
        inputs.append(line.strip())
        prompt = template.replace("{{prompt}}", user_prompt)
        prompt = prompt.replace("{{data}}", line.strip())
        prompts.append(prompt)
        if len(prompts) >= args.batch_size:
            reply = batch_llm_request(prompts, api_config)
            for x in zip(inputs, reply):
                print(json.dumps({"i": i, "in":x[0], "out":x[1].strip()}, ensure_ascii=False))
                i += 1

            dt = int((len(v) - i) * (time()-start)/i)
            sec = dt % 60
            min = (dt // 60) % 60
            h = dt // 3600

            if i < len(v):
                str_dt = ""
                if h > 0:
                    str_dt += f"{h}h "
                if min > 0:
                    str_dt += f"{min}m "
                if sec > 0:
                    str_dt += f"{sec}s "
                print(f'{int(100 * i / len(v)):4d}%, ETA: {str_dt}\r', file=sys.stderr, end='')

            prompts = []
            inputs = []

    if len(inputs) > 0:
        reply = batch_llm_request(prompts, api_config)
        for x in zip(inputs, reply):
            print(json.dumps({"i": i, "in":x[0],"out":x[1].strip()}, ensure_ascii=False))
            i += 1

    print(f'                                          \r', file=sys.stderr, end='')
else:
    prompt = template.replace("{{prompt}}", user_prompt)
    try:
        reply = filter_code(llm_request(prompt, api_config))

        if config["sandbox"]:
            cmd = [
                    "bwrap",
                    "--ro-bind", "/usr", "/usr",
                    "--symlink", "usr/lib64", "/lib64",
                    "--unshare-all",
                    "--new-session",
                    "python3", "-c", reply
                    ]
        else:
            cmd = ["python3", "-c", reply]

        process = subprocess.Popen(
            cmd,
            stdin=sys.stdin,
            text=True
        )

        process.communicate()

        if config['log_path'] is not None and not args.no_log:
            log_path = os.path.expanduser(config['log_path'])
            with open(log_path, 'a') as f:
                f.write(json.dumps({
                    "prompt": user_prompt,
                    "template_sha256": hashlib.sha256(template.encode()).hexdigest()[:32],
                    "payload": api_config['payload'],
                    "output": reply,
                    })+"\n")

            
    except Exception as e:
        traceback.print_exc()
    finally:
        if (args.debug or config['always_debug']) and 'reply' in globals():
            is_interactive = sys.stderr.isatty()
            if is_interactive:
                print("\033[36m", end='', file=sys.stderr)
            header  = "#!/usr/bin/env python3\n"
            print(header + reply.strip(), file=sys.stderr)
            if is_interactive:
                print("\033[0m", end='', file=sys.stderr)

